{ config, lib, pkgs, ... }:

let
  cfg = config.home.modules;

  # Foreign HM install (wsl) needs one extra topgrade step that a NixOS host
  # gets for free from `nixos-rebuild switch`: re-lock + re-apply this Home
  # Manager flake. Home.packages (the bundles included) update with it.
  # `--refresh` bypasses nix's 1h flake-eval cache — otherwise a freshly-pushed
  # lock update won't be picked up until the TTL expires.
  isForeign = cfg.wsl.enable;

  onlySteps =
    [ "system" "tldr" ]
    ++ lib.optionals isForeign [ "custom_commands" ];

  onlyLines = lib.concatMapStringsSep "\n" (s: "          \"${s}\",") onlySteps;

  foreignCommands = ''

    [commands]
    "home-manager (foreign)" = "home-manager switch --flake github:GooseRooster/home-manager#wsl --impure --refresh"
  '';
in
{
  xdg.configFile."topgrade.toml" = {
    force = true;
    text = ''
      # Topgrade — Nix-first config.
      #
      # Generated by modules/topgrade.nix; the wsl flavor appends a [commands]
      # entry that refreshes Home Manager (which owns the CLI bundles too — a
      # NixOS host gets the equivalent for free from `nixos-rebuild switch`).
      #
      # Restricts updates to a small, headless-friendly set. Steps whose tool
      # isn't installed are skipped automatically. Step names are topgrade's
      # snake_case identifiers; run `topgrade --dry-run` to preview.

      [misc]
      only = [
${onlyLines}
      ]

      assume_yes = true
      skip_notify = true
      cleanup    = true
    '' + lib.optionalString isForeign foreignCommands;
  };
}
