{ config, lib, pkgs, ... }:

let
  cfg = config.home.modules;

  # Foreign HM install (wsl / devcontainer) needs two extra topgrade steps
  # that a NixOS host gets for free from `nixos-rebuild switch`:
  #  1) re-lock + re-apply this Home Manager flake
  #  2) upgrade every `nix profile` entry (the nix-cli #base + #wsl bundles)
  # Both use `--refresh` to bypass nix's 1h flake-eval cache — otherwise a
  # freshly-pushed lock update won't be picked up until the TTL expires.
  isForeign = cfg.wsl.enable || cfg.devcontainer.enable;
  hmFlavor  = if cfg.devcontainer.enable then "devcontainer" else "wsl";

  onlySteps =
    [ "system" "tldr" ]
    ++ lib.optionals isForeign [ "custom_commands" ];

  onlyLines = lib.concatMapStringsSep "\n" (s: "          \"${s}\",") onlySteps;

  foreignCommands = ''

    [commands]
    "home-manager (foreign)" = "home-manager switch --flake github:GooseRooster/home-manager#${hmFlavor} --impure --refresh"
    "nix profile (foreign)"  = "nix profile upgrade --all --refresh"
  '';
in
{
  xdg.configFile."topgrade.toml" = {
    force = true;
    text = ''
      # Topgrade — Nix-first config.
      #
      # Generated by modules/topgrade.nix; the wsl/devcontainer flavors append
      # two [commands] entries that refresh Home Manager + the nix-cli profile
      # bundles (a NixOS host gets both for free from `nixos-rebuild switch`).
      #
      # Restricts updates to a small, headless-friendly set. Steps whose tool
      # isn't installed are skipped automatically. Step names are topgrade's
      # snake_case identifiers; run `topgrade --dry-run` to preview.

      [misc]
      only = [
${onlyLines}
      ]

      assume_yes = true
      skip_notify = true
      cleanup    = true
    '' + lib.optionalString isForeign foreignCommands;
  };
}
